version: "3"
services:
  api-database:
    image: mongo:3.2.4
    container_name: "api-database"
    ports:
      - 27017:27017
    command: --smallfiles
  api:
    image: ergaurav215/gaurav:personapi-docker-image
    ports:
      - 8080:8080
    links:
      - api-database
    environment:
    - "SPRING_PROFILES_ACTIVE=docker"